---
state_enter: false
state_exit: true
debug: false
logs:
  level: DEBUG
  token: ~
mongodb:
  authn: ~
  database: catalog_staging
pipelines:
  pipeline_uuid: ~
  pipeline_manager_id: pipelines-manager.prod
  pipeline_manager_nonce: ~
  job_manager_id: jobs-manager.prod
  job_manager_nonce: ~
  job_indexer_id: jobs-indexer.prod
  job_indexer_nonce: ~
  permission_manager: pems-agent.prod
  events_manager_id: events-manager.prod
  events_manager_nonce: ~
  process_uuid: 117a32a1-457c-5bfe-bded-ed0ca99e53f8
