---
debug: false
downloaded: downloaded.json
logs:
  level: DEBUG
  token: ~
mongodb:
  host: catalog
  port: 27017
  username: catalog
  password: catalog
  database: catalog_local

only_extant_files: false
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
