---
debug: false
downloaded: downloaded.json
logs:
  level: DEBUG
  token: ~
mongodb:
  database: catalog
  host: catalog.sd2e.org
  password: ~
  port: 27020
  username: catalog
only_extant_files: false
storagesystems:
  data-sd2e-community:
    posix_path: /work/projects/SD2E-Community/prod/data
