---
debug: false
logs:
  level: DEBUG
  token: ~
mongodb:
  authn: ~
  database: catalog_test
pipelines:
  pipeline_uuid: ~
  pipeline_manager_id: ~
  pipeline_manager_nonce: ~
  job_manager_id: MEzqaw4rkWZoK
  job_manager_nonce: ~
  job_indexer_id: Pw3eRxrqLZGmp
  job_indexer_nonce: ~
